apps/crud/models.py
from datetime import datetime
from apps.app import db, login_master
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class Item(db.Model):

    __tablename__ = "Items"

    id=db.Column(db.Integer, primary_key=True) #물품 고유 번호
    itemname=db.Column(db.String, unique=True, index=True)#물품 이름
    item_quantity=db.Column(db.Integer)#물품 수량
    time=db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)#입고 날짜
    item_description = db.Column(db.String)#물품 설명

class Representative(db.Model,UserMixin):

    __tablename__ = "Representative"

    id=db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    useremail = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)

    @property
    def password(self):
        raise AttributeError("읽어 드릴 수 없음")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def is_duplicate_email(self):
        return Representative.query.filter_by(useremail=self.useremail).first() is not None
    
@login_master.user_loader
def load_user(user_id):
    return Representative.query.get(user_id)

class Log(db.Model):
    __tablename__ ="Log"

    log_id=db.Column(db.Integer, primary_key=True) #순서
    log_itemname=db.Column(db.String, index=True)#물품 이름
    log_item_quantity=db.Column(db.Integer)#제품 수량 변경값 (+-)
    log_item_quantity_now=db.Column(db.Integer)#제품 물품 수량
    log_time=db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)#실시 시간
    log_representative=db.Column(db.String)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField,IntegerField,TextAreaField,DateTimeField
from wtforms.validators import DataRequired,Email,Length

#신규 물품 작성 폼
class ItemForm(FlaskForm):
    itemname = StringField(
        "물품명",
        validators=[
            DataRequired(message="물품명은 필수입니다."),
        ]
    )
    item_quantity=IntegerField(
        "수량",
        validators=[
            DataRequired(message="수량은 필수입니다."),
        ]
    )
    time=DateTimeField(
        "날짜 시간",
        format="%Y-%m-%d %H:%M",
        validators=[
            DataRequired(message="날짜,시간을 정확히 입력해주세요. 예시)2020-04-07 17:26")
        ]
    )
    item_description=TextAreaField(
        "물품 설명",
        validators=[
            DataRequired(message="설명을 제대로 작성해주세요.")
        ]
    )
    submit = SubmitField("신규 물품 등록")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, jsonify, render_template,redirect,url_for,flash,request
from sqlalchemy import JSON
from apps.crud.forms import ItemForm
from apps.app import db
from apps.crud.models import Item,Log
from datetime import datetime
from flask_login import current_user, login_required

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)

@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html")

@crud.route("/goods/new",methods=["GET","POST"])
@login_required
def create_goods():
    form = ItemForm()
    if form.validate_on_submit():

        item = Item(
            itemname=form.itemname.data,
            item_quantity=form.item_quantity.data,
            time=form.time.data,
            item_description=form.item_description.data,
        )
        log= Log(
            log_itemname=form.itemname.data,
            log_item_quantity=form.item_quantity.data,
            log_item_quantity_now=form.item_quantity.data,
            log_time=form.time.data,
            log_representative = current_user.username
        )
        db.session.add(item)
        db.session.add(log)
        db.session.commit()
        return redirect(url_for("crud.goods"))
    return render_template("crud/create.html", form=form)

@crud.route("/goods")
@login_required
def goods():
    form = ItemForm()
    goods=Item.query.all()
    logs=Log.query.all()
    return render_template("crud/goods.html", goods = goods, logs=logs, form=form)

@crud.route("/goods/<goods_id>", methods=["GET","POST"])
@login_required
def change_quantity(goods_id):
    form = ItemForm()
    goods = Item.query.filter_by(id=goods_id).first()
    if form.validate_on_submit():
        log= Log(
            log_itemname=form.itemname.data,
            log_item_quantity=(form.item_quantity.data-goods.item_quantity),
            log_item_quantity_now=form.item_quantity.data,
            log_time=datetime.now(),
            log_representative = current_user.username
        )
        goods.itemname=form.itemname.data
        goods.item_quantity=form.item_quantity.data
        goods.time=datetime.now()
        goods.item_description=form.item_description.data

        db.session.add(goods)
        db.session.add(log)
        db.session.commit()
        return redirect(url_for("crud.goods"))
    form.item_description.data = goods.item_description
    return render_template("crud/change_quantity.html",item = goods,form=form)

    
@crud.route("/goods/<goods_itemname>/delete", methods=["POST"])
def delete_goods(goods_itemname):
    item = Item.query.filter_by(itemname=goods_itemname).first()
    db.session.delete(item)
    log= Log(
            log_itemname=goods_itemname,
            log_item_quantity=None,
            log_item_quantity_now=None,
            log_time=datetime.now(),
            log_representative = current_user.username,
        )
    db.session.add(log)
    db.session.commit()
    return redirect(url_for("crud.goods"))

@crud.route("/log_delete", methods=["POST"])
def delete_log():
    db.session.query(Log).delete()
    db.session.commit()
    flash("로그가 삭제되었습니다.", "success")
    return redirect(url_for("crud.goods"))

@crud.route("/logvalue", methods=["POST"])
def log_value():
    if request.method == 'POST':
        data = request.json 
        value = data.get('value') 

        if value=="전체":
            logs =Log.query.all()
        else:
            logs =Log.query.filter_by(log_itemname=value).all()

        serialized_logs = []
        for log in logs:
            serialized_log = {
                "log_id": log.log_id,
                "log_itemname": log.log_itemname,
                "log_item_quantity": log.log_item_quantity,
                "log_item_quantity_now": log.log_item_quantity_now,
                "log_time": log.log_time.strftime("%Y-%m-%d %H:%M:%S"),
                "log_representative": log.log_representative
            }
            serialized_logs.append(serialized_log)
        return jsonify(serialized_logs)
            
# @crud.route("/logvalue/<value>")
# def log_value_view(value):
#     print(value)
#     form = ItemForm()
#     goods=Item.query.all()
#     logs=Log.query.filter_by(log_itemname=value).all()
#     print("zz: " , logs)
#     return render_template("crud/goods.html", goods = goods, logs=logs, form=form)
    
    
    

    # data = request.json  # 클라이언트에서 전달된 JSON 데이터를 가져옴
    # value = data.form['value']  # JSON 데이터에서 'value' 키의 값을 가져옴
    # form = ItemForm()
    # goods=Item.query.all()
    # logs=Log.query.filter_by(log_itemname = value).all()
    # return render_template("crud/goods.html", goods = goods, logs=logs, form=form)

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('crud.static',filename='style.css')}}"/>
</head>
<body>
    <div>
        {% if current_user.is_authenticated %}
        <span class="login">
            <span>관리자 : </span>
            <span>{{ current_user.username }}</span>
            <span><a href="{{url_for('auth.logout')}}">로그아웃</a></span>
        </span>
        {% endif %}
    </div>
    {% block content %}{% endblock %}
</body>
</html>

apps/crud/templates/crud/change_quantity.html
{% extends "crud/base.html" %}
{% block title%}수량 변경{% endblock %}
{% block content %}
<div class="container">
    <h2>수량 변경</h2>
    <form
        action="{{ url_for('crud.change_quantity', goods_id=item.id) }}"
        method="POST"
        novalidate="novalidate"
    >
        {{form.csrf_token}}
        <p >
            {{ form.itemname.label}} {{form.itemname(placeholder="제품명", value=item.itemname,readonly=True)}}
        </p>
        {% for error in form.itemname.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{ form.item_quantity.label}} {{form.item_quantity(placeholder=item.item_quantity)}}
        </p>
        {% for error in form.item_quantity.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{ form.time.label("마지막 변경 시간")}} {{form.time(placeholder="날짜 시간", value=item.time.strftime('%Y-%m-%d %H:%M'), readonly=True)}}
        </p>
        {% for error in form.time.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{ form.item_description.label}} {{ form.item_description(placeholder="제품 설명", value=item.item_description, readonly=True) }}
        </p>
        {% for error in form.item_description.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p><input type="submit" value="변경"></p>
    </form>
</div>
{% endblock %}

apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title%}신규 물품 등록{% endblock %}
{% block content %}
<div class="container">
    <h2>신규 물품 등록</h2>
    <form
        action="{{url_for('crud.create_goods')}}"
        method="POST"
        novalidate="novalidate"
    >
        {{form.csrf_token}}
        <p>
            {{ form.itemname.label}} {{form.itemname(placeholder="물품명")}}
        </p>
        {% for error in form.itemname.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{ form.item_quantity.label}} {{form.item_quantity(placeholder="제품 수량")}}
        </p>
        {% for error in form.item_quantity.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{ form.time.label}} {{form.time(placeholder="날짜 시간" )}}
        </p>
        {% for error in form.time.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>
            {{ form.item_description.label}} {{form.item_description(placeholder="제품 설명")}}
        </p>
        {% for error in form.item_description.errors %}
        <span style="color: red;">{{error}}</span>
        {% endfor %}
        <p>{{ form.submit() }}</p>
    </form>
</div>
{% endblock %}

apps/crud/templates/crud/goods.html
{% extends "crud/base.html" %}
{% block title%}제품 목록{% endblock %}
{% block content %}
    <div class="title">
    <h2 class="h2">제품 목록</h2>
    </div>
    
    <div class="container">
    <p class="link"><a class="a" href="{{url_for('crud.create_goods',filename='style.css')}}">신규 제품 등록</a></p>
    <table class="table_goods">
        <tr>
            <th>물품 ID</th>
            <th>물품명</th>
            <th>물품 수량</th>
            <th>시간</th>
            <th>물품 설명</th>
        </tr>
        {% for item in goods%}
        <tr>
            <td>
                {{ item.id }}
            </td>
            <td>{{ item.itemname}}</td>
            <td>{{ item.item_quantity}}</td>
            <td>{{ item.time.strftime('%Y-%m-%d %H:%M')}}</td>
            <td>{{ item.item_description}}</td>
            <td>
                <a href="{{ url_for('crud.change_quantity',goods_id=item.id)}}"><button>수량변경</button></a>
            </td>
            <td>
                <form
                    action="{{url_for('crud.delete_goods', goods_itemname = item.itemname)}}"
                    method="POST"
                >
                    {{ form.csrf_token }}
                    <input type="submit" value="삭제">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
    <details class="details">
        <summary>LOG보기</summary>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        <select id="goods" name="items">
            <option value="전체">전체</option>
            {% for item in goods%}
            <option value={{item.itemname}}>{{ item.itemname }}</option>
            {% endfor %}
        </select>

        <ul id="log_value">
            {% for log in logs %}
            <li class="log-item">
                {{log.log_id}}
                {{log.log_itemname}}
                <span>입/출고:</span>
                {% if log.log_item_quantity is not none %}
                    {% if log.log_item_quantity > 0 %}
                        <span>+</span>{{ log.log_item_quantity }}
                    {% else %}
                        {{ log.log_item_quantity }}
                    {% endif %}
                {% else %}
                    <span>삭제</span>
                {% endif %}
                <span>현재 수량:</span>
                {% if log.log_item_quantity is not none %}
                    {{log.log_item_quantity_now}}
                {% else %}
                    <span>삭제</span>
                {% endif %}
                <span>시간:</span>{{log.log_time.strftime('%Y-%m-%d %H:%M:%S')}}
                <span>관리자:</span>{{log.log_representative}}
                
            </li>
            {% endfor %}
            
        </ul>
        <form
                action="{{url_for('crud.delete_log')}}"
                method="POST"
                onsubmit="return Delete()"
            >
                {{ form.csrf_token }}
                <input type="submit" value="LOG삭제" >
        </form>
    </details>

    </div>

    <!-- <script>
        let a = document.querySelector("#goods")
        a.addEventListener("change",()=>{
            let b = document.querySelector("#log_value")
            b.innerHTML=""
        })

    </script> -->
    <script>
        let a = document.querySelector("#goods")
        let csrf_token_value = "{{ form.csrf_token._value() }}";
        a.addEventListener("change",()=>{
            let b = document.querySelector("#goods")
            fetch("{{ url_for('crud.log_value')}}", {
                method :"POST",
                headers:{
                    'Content-Type': 'application/json;charset=utf-8',
                    "X-CSRFToken": csrf_token_value,  // CSRF 토큰 값
                },
                body : JSON.stringify({ // 여기서 사용
                        value: b.value
                    }),
            })
            .then(response => response.json()) // JSON 형식으로 파싱
            .then(data => {
                
                let a = document.querySelector("#log_value")
                a.innerHTML=""
                for(let i=0; i<data.length; i++){
                    let b = document.createElement("li")
                    if (data[i].log_item_quantity == null){
                        data[i].log_item_quantity = "삭제"
                    }
                    if (data[i].log_item_quantity_now == null){
                        data[i].log_item_quantity_now = "삭제"
                    }
                    b.textContent =
                                data[i].log_id+" "+
                                data[i].log_itemname+" 입/출고: "+
                                data[i].log_item_quantity+" 현재 수량: "+
                                data[i].log_item_quantity_now+" 시간: "+
                                data[i].log_time+" 관리자: "+
                                data[i].log_representative
                    a.appendChild(b)
                }
            })

        })

    </script>

    <script>
        function Delete() {
            if (confirm("정말 삭제하시겠습니까?")) {
                return true
            }else{
                return false
            }
        }
    </script>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title%}이것은 테스트 입니다.{% endblock %}
{% block content %}
    <p>테스트 용 입니다.</p>
{% endblock %}